from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/dna-seq-benchmark as a module
module dna_seq_benchmark:
    snakefile: 
        github("snakemake-workflows/dna-seq-benchmark", path="workflow/Snakefile", commit="f265c4b57ee01197069e611259f0e7491f1a3a29")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/dna-seq-benchmark
use rule * from dna_seq_benchmark
