from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/dna-seq-benchmark as a module
module dna_seq_benchmark:
    snakefile: 
        github("snakemake-workflows/dna-seq-benchmark", path="workflow/Snakefile", commit="ac525a4b1f2cc77d846d2fd7d02ef1ebdb0022fc")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/dna-seq-benchmark
use rule * from dna_seq_benchmark
