from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/dna-seq-benchmark as a module
module dna_seq_benchmark:
    snakefile: 
        github("snakemake-workflows/dna-seq-benchmark", path="workflow/Snakefile", tag="v1.17.0")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/dna-seq-benchmark
use rule * from dna_seq_benchmark
