variant-calls:
  # WES with BQSR
  seqc2-wes-qbic-freebayes:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: freebayes 1.3.10
      annotation: VEP 115.2
    path: seqc2/bqsr/tumor-wes_vs_normal-wes.freebayes.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-wes_tumor-wes
    benchmark: seqc2-wes
    vaf-field:
      field: INFO
      name: AF
    rename-contigs: true
  seqc2-wes-qbic-mutect2:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: mutect2 2.2
      annotation: VEP 115.2
    path: seqc2/bqsr/tumor-wes_vs_normal-wes.mutect2.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-wes_tumor-wes
    benchmark: seqc2-wes
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true
  seqc2-wes-qbic-strelka:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: strelka 2.9.10
      annotation: VEP 115.2
    path:
      snvs: seqc2/bqsr/tumor-wes_vs_normal-wes.strelka.somatic_snvs.vcf.gz
      indels: seqc2/bqsr/tumor-wes_vs_normal-wes.strelka.somatic_indels.vcf.gz
    subcategory: qbic
    tumor_sample_name: TUMOR
    benchmark: seqc2-wes
    # vaf-field: # strelka reports no vaf-field
    rename-contigs: true
  seqc2-wes-qbic-muse:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: muse 2.1.2
      annotation: VEP 115.2
    path: seqc2/bqsr/tumor-wes_vs_normal-wes.muse.vcf.gz
    subcategory: qbic
    tumor_sample_name: TUMOR
    benchmark: seqc2-wes
    # vaf-field: # muse reports no vaf-field
    rename-contigs: true
  seqc2-wes-qbic-varlociraptor-fdr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: varlociraptor 8.7.4
      annotation:
    path: seqc2/bqsr/tumor-wes_vs_normal-wes.freebayes.somatic.varlociraptor.fdr-controlled.bcf
    tumor_sample_name: tumor
    benchmark: seqc2-wes
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true
  seqc2-wes-qbic-varlociraptor-strelka:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: strelka 2.9.10
      annotation:
    path: seqc2/bqsr/tumor-wes_vs_normal-wes.strelka.somatic.varlociraptor.fdr-controlled.bcf
    tumor_sample_name: tumor
    benchmark: seqc2-wes
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true

  # WES skip-bqsr
  seqc2-wes-qbic-freebayes-skip-bqsr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: freebayes 1.3.10
      annotation: VEP 115.2
    path: seqc2/no-bqsr/tumor-wes_vs_normal-wes.freebayes.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-wes_tumor-wes
    benchmark: seqc2-wes
    vaf-field:
      field: INFO
      name: AF
    rename-contigs: true
  seqc2-wes-qbic-mutect2-skip-bqsr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: mutect2 2.2
      annotation: VEP 115.2
    path: seqc2/no-bqsr/tumor-wes_vs_normal-wes.mutect2.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-wes_tumor-wes
    benchmark: seqc2-wes
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true
  seqc2-wes-qbic-strelka-skip-bqsr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: strelka 2.9.10
      annotation: VEP 115.2
    path:
      snvs: seqc2/no-bqsr/tumor-wes_vs_normal-wes.strelka.somatic_snvs.vcf.gz
      indels: seqc2/no-bqsr/tumor-wes_vs_normal-wes.strelka.somatic_indels.vcf.gz
    subcategory: qbic
    tumor_sample_name: TUMOR
    benchmark: seqc2-wes
    # vaf-field: # strelka reports no vaf-field
    rename-contigs: true
  
  # FFPE with BQSR
  seqc2-ffpe-qbic-freebayes:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: freebayes 1.3.10
      annotation: VEP 115.2
    path: seqc2/bqsr/tumor-ffpe_vs_normal-ffpe.freebayes.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-ffpe_tumor-ffpe
    benchmark: seqc2-ffpe
    vaf-field:
      field: INFO
      name: AF
    rename-contigs: true
  seqc2-ffpe-qbic-mutect2:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: mutect2 2.2
      annotation: VEP 115.2
    path: seqc2/bqsr/tumor-ffpe_vs_normal-ffpe.mutect2.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-ffpe_tumor-ffpe
    benchmark: seqc2-ffpe
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true
  seqc2-ffpe-qbic-strelka:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: strelka 2.9.10
      annotation: VEP 115.2
    path:
      snvs: seqc2/bqsr/tumor-ffpe_vs_normal-ffpe.strelka.somatic_snvs.vcf.gz
      indels: seqc2/bqsr/tumor-ffpe_vs_normal-ffpe.strelka.somatic_indels.vcf.gz
    subcategory: qbic
    tumor_sample_name: TUMOR
    benchmark: seqc2-ffpe
    # vaf-field: # strelka reports no vaf-field
    rename-contigs: true
  seqc2-ffpe-qbic-muse:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: muse 2.1.2
      annotation: VEP 115.2
    path: seqc2/bqsr/tumor-ffpe_vs_normal-ffpe.muse.vcf.gz
    subcategory: qbic
    tumor_sample_name: TUMOR
    benchmark: seqc2-ffpe
    # vaf-field: # muse reports no vaf-field
    rename-contigs: true
  seqc2-ffpe-qbic-varlociraptor-fdr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: varlociraptor 8.7.4
      annotation:
    path: seqc2/bqsr/tumor-ffpe_vs_normal-ffpe.freebayes.somatic.varlociraptor.fdr-controlled.bcf
    tumor_sample_name: tumor
    benchmark: seqc2-ffpe
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true
  seqc2-ffpe-qbic-varlociraptor-strelka:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: strelka 2.9.10
      annotation:
    path: seqc2/bqsr/tumor-ffpe_vs_normal-ffpe.strelka.somatic.varlociraptor.fdr-controlled.bcf
    tumor_sample_name: tumor
    benchmark: seqc2-ffpe
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true

  # FFPE skip-bqsr
  seqc2-ffpe-qbic-freebayes-skip-bqsr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: freebayes 1.3.10
      annotation: VEP 115.2
    path: seqc2/no-bqsr/tumor-ffpe_vs_normal-ffpe.freebayes.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-ffpe_tumor-ffpe
    benchmark: seqc2-ffpe
    vaf-field:
      field: INFO
      name: AF
    rename-contigs: true
  seqc2-ffpe-qbic-mutect2-skip-bqsr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: mutect2 2.2
      annotation: VEP 115.2
    path: seqc2/no-bqsr/tumor-ffpe_vs_normal-ffpe.mutect2.filtered.vcf.gz
    subcategory: qbic
    tumor_sample_name: seqc2-ffpe_tumor-ffpe
    benchmark: seqc2-ffpe
    vaf-field:
      field: FORMAT
      name: AF
    rename-contigs: true
  seqc2-ffpe-qbic-strelka-skip-bqsr:
    labels:
      site: qbic
      workflow-management: Nextflow 25.04.8
      pipeline: nf-core/sarek 3.6.0
      adapter-trimming: fastp 0.24.0
      read-mapping: bwamem 0.7.18
      recalibration: gatk4 4.6.1.0
      variant-detection: strelka 2.9.10
      annotation: VEP 115.2
    path:
      snvs: seqc2/no-bqsr/tumor-ffpe_vs_normal-ffpe.strelka.somatic_snvs.vcf.gz
      indels: seqc2/no-bqsr/tumor-ffpe_vs_normal-ffpe.strelka.somatic_indels.vcf.gz
    subcategory: qbic
    tumor_sample_name: TUMOR
    benchmark: seqc2-ffpe
    # vaf-field: # strelka reports no vaf-field
    rename-contigs: true

# Optional for testing: limit to first 10000 reads
limit-reads: false

# whether evaluation shall happen on grch37
reference-genome: grch38

# maximum number of entries in the FP and FN tables
# (this might be exceeded because each chromosome is always fully included)
max-fp-fn-entries: 300
